name: build-xsdk
description: 'Build xsdk with given command'
inputs:
  cmd:
    description: 'build command'
    required: true
    default: ./bin/spack install xsdk
runs:
  using: "composite"
  steps: 
#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#     - uses: actions/checkout@v2
    
    # Runs a set of commands before main scripts using the runners shell
    - name: before_script 
      run: |
        date
        hostname
        if [ -f /etc/os-release ]; then grep PRETTY_NAME /etc/os-release; nproc; lscpu |grep 'Model name'; fi
        if [ -f /usr/bin/sw_vers ]; then /usr/bin/sw_vers ;sysctl -n hw.ncpu machdep.cpu.brand_string ; fi
        if [ ! -z ${RM_MODULES+x} ]; then printf "removing modules - ${RM_MODULES}\n"; module list; module remove ${RM_MODULES}; fi
        if [ ! -z ${LOAD_MODULES+x} ]; then printf "loading modules - ${LOAD_MODULES}\n"; module load ${LOAD_MODULES}; module list; fi
      shell: bash
    
    # Runs build scripts
    - name: build
      run: ${{ inputs.cmd }}
      shell: bash

    # Runs a set of commands after main scripts using the runners shell
    - name: after_script
      if: ${{ always() }}
      run: |
        date
        ./bin/spack find -v


